# name: promise catch
# key: pc
# --
.catch(err => ${1:{}})